apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  # namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: us-central1-docker.pkg.dev/bright-feat-471605-t7/app-images/demo-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['kubectl.kubernetes.io/restartedAt']
